### ISSUE TITLE
but y doe? 

### ISSUE THREAD

**Issue by HunterEl** [ranneyd/kappa.tv#1]
<img width="1435" alt="screen shot 2015-11-03 at 9 26 43 pm" src="https://cloud.githubusercontent.com/assets/6547952/10930526/cee62a20-8273-11e5-94ae-07b8132738b5.png">

**Comment by ranneyd** [comment]
fixed in the last commit.

Basically jquery ui's resizable and draggable both pass a "ui" object to a callback. Resizable's gives you size and position, draggable only gives you position. So dragging was trying to set width and height but it wasn't there. I had just thrown this in because I was dragging but keeping the default size so it was only saving the position in the cookie and just using arbitrary sizes. I now just find the size of the element with jquery instead
